export const TableData = [
  {
    attached_groups: "Kevins VM Groups",
    id: "1",
    key: 1,
    name: "Load Balancer 3",
    port: 3000,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Disabled",
    btn: 1,
    isEditable: true,
  },
  {
    attached_groups: "Maureens VM Groups",
    id: "2",
    key: 2,
    name: "Load Balancer 1",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 2,
  },
  {
    attached_groups: "Andrews VM Groups",
    id: "3",
    key: 3,
    name: "Load Balancer 2",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 3,
  },
  {
    attached_groups: "Marcs VM Groups",
    id: "4",
    key: 4,
    name: "Load Balancer 6",
    port: 3000,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Disabled",
    btn: 4,
  },
  {
    attached_groups: "Mels VM Groups",
    id: "5",
    key: 5,
    name: "Load Balancer 4",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 5,
  },
  {
    attached_groups: "Ronjas VM Groups",
    id: "6",
    key: 6,
    name: "Load Balancer 5",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 6,
  },
  {
    attached_groups: "Andrews VM Groups",
    id: "7",
    key: 7,
    name: "Load Balancer 2",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 3,
  },
  {
    attached_groups: "Marcs VM Groups",
    id: "8",
    key: 8,
    name: "Load Balancer 6",
    port: 3000,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Disabled",
    btn: 4,
  },
  {
    attached_groups: "Mels VM Groups",
    id: "9",
    key: 9,
    name: "Load Balancer 4",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 5,
  },
  {
    attached_groups: "Ronjas VM Groups",
    id: "10",
    key: 10,
    name: "Load Balancer 5",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 6,
  },
  {
    attached_groups: "Mels VM Groups",
    id: "11",
    key: 11,
    name: "Load Balancer 4",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 5,
  },
  {
    attached_groups: "Ronjas VM Groups",
    id: "12",
    key: 12,
    name: "Load Balancer 5",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 6,
  },
  {
    attached_groups: "Andrews VM Groups",
    id: "13",
    key: 13,
    name: "Load Balancer 2",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 3,
  },
  {
    attached_groups: "Marcs VM Groups",
    id: "14",
    key: 14,
    name: "Load Balancer 6",
    port: 3000,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Disabled",
    btn: 4,
  },
  {
    attached_groups: "Mels VM Groups",
    id: "15",
    key: 15,
    name: "Load Balancer 4",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 5,
  },
  {
    attached_groups: "Ronjas VM Groups",
    id: "16",
    key: 16,
    name: "Load Balancer 5",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 6,
  },
  {
    attached_groups: "Andrews VM Groups",
    id: "17",
    key: 17,
    name: "Load Balancer 2",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 3,
  },
  {
    attached_groups: "Marcs VM Groups",
    id: "18",
    key: 18,
    name: "Load Balancer 6",
    port: 3000,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Disabled",
    btn: 4,
  },
  {
    attached_groups: "Mels VM Groups",
    id: "19",
    key: 19,
    name: "Load Balancer 4",
    port: 443,
    protocol: "HTTP",
    rule: "Round robin",
    status: "Starting",
    btn: 5,
  },
  {
    attached_groups: "Ronjas VM Groups",
    id: "20",
    key: 20,
    name: "Load Balancer 5",
    port: 80,
    protocol: "HTTP",
    rule: "DNS delegation",
    status: "Active",
    btn: 6,
  },
];
